<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-04-23T18:06:41Z" name="Default suite" finished-at="2018-04-23T18:07:05Z" duration-ms="24170">
    <groups>
    </groups>
    <test started-at="2018-04-23T18:06:41Z" name="Default test" finished-at="2018-04-23T18:07:05Z" duration-ms="24170">
      <class name="testCases.LoginTest">
        <test-method is-config="true" signature="_beforeTest()[pri:0, instance:testCases.LoginTest@548e6d58]" started-at="2018-04-23T18:06:41Z" name="_beforeTest" finished-at="2018-04-23T18:06:56Z" duration-ms="15055" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _beforeTest -->
        <test-method signature="TestValid_Login()[pri:0, instance:testCases.LoginTest@548e6d58]" started-at="2018-04-23T18:06:56Z" name="TestValid_Login" finished-at="2018-04-23T18:07:05Z" duration-ms="8431" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Password is required.] but found [Password is required12.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Password is required.] but found [Password is required12.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pageObjects.Home_Page.verifyPwd_Required(Home_Page.java:90)
at appModule.Login_Action.Test_Valid_Login(Login_Action.java:37)
at testCases.LoginTest.TestValid_Login(LoginTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestValid_Login -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.LoginTest@548e6d58]" started-at="2018-04-23T18:07:05Z" name="getResult" finished-at="2018-04-23T18:07:05Z" duration-ms="116" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestValid_Login status=FAILURE method=LoginTest.TestValid_Login()[pri:0, instance:testCases.LoginTest@548e6d58] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="_afterMethod()[pri:0, instance:testCases.LoginTest@548e6d58]" started-at="2018-04-23T18:07:05Z" name="_afterMethod" finished-at="2018-04-23T18:07:05Z" duration-ms="319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _afterMethod -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:testCases.LoginTest@548e6d58]" started-at="2018-04-23T18:07:05Z" name="endReport" finished-at="2018-04-23T18:07:05Z" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- testCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
